version: '3'

services:

  contract:
    build: 
      context: enigma-contract
      dockerfile: Dockerfile.ganache-cli
      args:
        - SSH_PRIVATE_KEY
        - GIT_BRANCH_CONTRACT=${GIT_BRANCH_CONTRACT}
    stdin_open: true
    tty: true
    volumes:
        - built_contracts:/home/node/enigma-contract/build/contracts
    networks:
        - net 

  surface:
    build: 
      context: surface
      args:
        - SSH_PRIVATE_KEY
        - GIT_BRANCH_SURFACE=${GIT_BRANCH_SURFACE}
    depends_on:
      - contract
    stdin_open: true
    tty: true
    volumes:
        - built_contracts:/var/lib/built_contracts
        - ./surface/wait_launch.bash:/root/wait_launch.bash:ro
        - ./surface/docker_config.bash:/root/docker_config.bash:ro
    hostname: enigma_surface_${WORKER_INDEX}
    networks:
        - net

  core:
    build:
      context: core
      args:
        - SSH_PRIVATE_KEY
        - GIT_BRANCH_CORE=${GIT_BRANCH_CORE}
    stdin_open: true
    tty: true
    devices:
      - "/dev/isgx:/dev/isgx"
    expose:
      - "5552"
    hostname: enigma_core_${WORKER_INDEX}
    networks:
      - net

networks:
    net:

volumes:
  built_contracts:
